parameters:
    ezpublish.fieldType.owenhancedselection.class: 'Ow\Bundle\OwEnhancedSelectionBundle\FieldType\OwEnhancedSelection\Type'
    ezpublish.fieldType.owenhancedselection.converter.class: 'Ow\Bundle\OwEnhancedSelectionBundle\Persistence\Legacy\Content\FieldValue\Converter\OwEnhancedSelection'
    doctrine.orm.entity_manager: 'Doctrine\ORM\EntityManager'

services:
    ezpublish.fieldType.owenhancedselection:
        class: %ezpublish.fieldType.owenhancedselection.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: owenhancedselection}

    ezpublish.fieldType.owenhancedselection.converter:
        class: %ezpublish.fieldType.owenhancedselection.converter.class%
        arguments: [@ezpublish.api.storage_engine.legacy.dbhandler, @service_container]
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: owenhancedselection}